/****************************************************************************
 *  License : All rights reserved for TES Electronic Solutions GmbH
 *            See included /docs/license.txt for details
 *  Project : D/AVE HD
 *  Purpose : Inline function bodies
 ****************************************************************************
 * Version Control Information :
 *  $Revision: 510 $
 *  $Date: 2019-09-30 11:32:37 +0900 (月, 30 9 2019) $
 *  $LastChangedBy: a5110279 $
 ****************************************************************************
 * Change History (autogenerated):
 ****************************************************************************/    

#ifndef DAVEHD_DRIVER_INL_H_INCLUDED
#define DAVEHD_DRIVER_INL_H_INCLUDED

/*----------------------------------------------------------------------------------------------------------*/
#include "davehd_internal.h"

/*----------------------------------------------------------------------------------------------------------*/
/* State functions */
/**/
#include "davehd_driver_blu_inl.h"    /* Blend Unit related functions*/
#include "davehd_driver_col_inl.h"    /* Color Unit related functions*/
#include "davehd_driver_psu_inl.h"    /* Pixel Selection related functions*/
#include "davehd_driver_txp_inl.h"    /* Texture Unit related functions*/
#include "davehd_driver_zsu_inl.h"    /* ZSA Unit related functions*/
#include "davehd_driver_buf_inl.h"    /* Buffer related functions*/

/*----------------------------------------------------------------------------------------------------------*/
/* Utility functions */
/**/
#include "davehd_util_inl.h" 

/*----------------------------------------------------------------------------------------------------------*/

#endif /*DAVEHD_DRIVER_INL_H_INCLUDED*/
