/****************************************************************************
 *  License : All rights reserved for TES Electronic Solutions GmbH
 *            See included /docs/license.txt for details
 *  Project : D/AVE HD
 *  Purpose : Hardware specific compiletime settings
 ****************************************************************************
 * Version Control Information :
 *  $Revision: 510 $
 *  $Date: 2019-09-30 11:32:37 +0900 (月, 30 9 2019) $
 *  $LastChangedBy: a5110279 $
 ****************************************************************************
 * Change History (autogenerated):
 ****************************************************************************/
/*----------------------------------------------------------------------------------------------------------*/

#ifndef DAVEHD_REGISTERFILE_H_INCLUDED
#define DAVEHD_REGISTERFILE_H_INCLUDED


#include "davehd_registerfile_default.h"

#endif /* DAVEHD_REGISTERFILE_H_INCLUDED */
