/****************************************************************************
 *  License : All rights reserved for TES Electronic Solutions GmbH
 *            See included /docs/license.txt for details
 *  Project : D/AVE HD
 *  Purpose : Hardware specific compiletime settings
 ****************************************************************************
 * Version Control Information :
 *  $Revision: 510 $
 *  $Date: 2019-09-30 11:32:37 +0900 (月, 30 9 2019) $
 *  $LastChangedBy: a5110279 $
 ****************************************************************************
 * Change History (autogenerated):
 ****************************************************************************/
/*----------------------------------------------------------------------------------------------------------*/
/* Gets platform constrained registermap, default config for all other*/
/**/
#ifndef DAVEHD_REGISTERMAP_H_INCLUDED
#define DAVEHD_REGISTERMAP_H_INCLUDED

#ifdef RENESAS_D1X
  #include "davehd_registermap_ree.h"
#else
  #include "davehd_registermap_default.h"
#endif

#endif /* DAVEHD_REGISTERMAP_H_INCLUDED */
