/****************************************************************************
 *  License : All rights reserved for TES Electronic Solutions GmbH
 *            See included /docs/license.txt for details
 *  Project : D/AVE HD
 *  Purpose : Handling of hardware errors.
 ****************************************************************************
 * Version Control Information :
 *  $Revision: 510 $
 *  $Date: 2019-09-30 11:32:37 +0900 (月, 30 9 2019) $
 *  $LastChangedBy: a5110279 $
 ****************************************************************************
 * Change History (autogenerated):
 ****************************************************************************/    

#ifndef DAVEHD_KERNEL_ERROR_H_INCLUDED
#define DAVEHD_KERNEL_ERROR_H_INCLUDED

#include "davehd_types.h"
#include "davehd_kernel_driver.h"

/*----------------------------------------------------------------------------------------------------------*/

void dhd_gpu_process_error(dhd_gpu_device_data_t *a_device);

/*----------------------------------------------------------------------------------------------------------*/

#endif /*DAVEHD_KERNEL_ERROR_H_INCLUDED*/
