/****************************************************************************
 *  License : All rights reserved for TES Electronic Solutions GmbH
 *            See included /docs/license.txt for details
 *  Project : D/AVE HD
 *  Purpose : Job scheduling and state store/restore management
 ****************************************************************************
 * Version Control Information :
 *  $Revision: 510 $
 *  $Date: 2019-09-30 11:32:37 +0900 (月, 30 9 2019) $
 *  $LastChangedBy: a5110279 $
 ****************************************************************************
 * Change History (autogenerated):
 ****************************************************************************/    

#ifndef DAVEHD_KERNEL_SCHEDULE_H_INCLUDED
#define DAVEHD_KERNEL_SCHEDULE_H_INCLUDED

#include "davehd_types.h"

/*----------------------------------------------------------------------------------------------------------*/

dhd_enum_t dhd_gpu_schedule_job(dhd_gpu_device_data_t *a_device);
dhd_uint32_t dhd_gpu_mark_finished_jobs(dhd_gpu_device_data_t *a_device);
dhd_uint32_t dhd_gpu_query_jobsync(const dhd_gpu_device_data_t *a_device, dhd_bool_t a_direct);
dhd_uint32_t dhd_gpu_yield(dhd_gpu_device_data_t *a_device);

/*----------------------------------------------------------------------------------------------------------*/

#endif /*DAVEHD_KERNEL_SCHEDULE_H_INCLUDED*/
